# Generated by Django 5.0.1 on 2024-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/img/avatar.jpg', upload_to='static/profile_pics'),
        ),
    ]
